/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.mayo.mprc.io.mgf;

import edu.mayo.mprc.utilities.FileUtilities;
import org.proteomecommons.io.mgf.MascotGenericFormatPeakList;

import java.io.File;
import java.util.Collection;
import java.util.TreeSet;

/**
 * Filters spectra from an mgf file, separating "good" from "bad" ones.
 */
public final class MGFFilteredFileGenerator {

	private MGFFilteredFileGenerator() {
	}

	/**
	 * Separates spectra from given input .mgf files into two files (accepted, rejected), based on a filter.
	 * If either of the files is null, the spectra that would go into that file are lost.
	 *
	 * @param sourceMgf   Input mgf file. This file will not be modified in any way.
	 * @param acceptedMgf Accepted spectra mgf (for spectra where filter returns true)
	 * @param rejectedMgf Rejected spectra mgf (for spectra where filter returns false).
	 * @param filter      Filter that either accepts or rejects each particular spectrum.
	 */
	public static MgfFilteredSpectraCount filterMgfFile(final File sourceMgf, final File acceptedMgf, final File rejectedMgf, final MgfPeakListFilter filter) {
		int totalSpectra = 0;
		int acceptedSpectra = 0;
		int rejectedSpectra = 0;

		MGFPeakListReader sourceMgfReader = null;
		MGFPeakListWriter acceptedMgfWriter = null;
		MGFPeakListWriter rejectedMgfWriter = null;

		try {
			sourceMgfReader = new MGFPeakListReader(sourceMgf);
			if (acceptedMgf != null) {
				acceptedMgfWriter = new MGFPeakListWriter(acceptedMgf);
			}

			if (rejectedMgf != null) {
				rejectedMgfWriter = new MGFPeakListWriter(rejectedMgf);
			}

			MascotGenericFormatPeakList peakList = null;

			while ((peakList = sourceMgfReader.nextPeakList()) != null) {
				totalSpectra++;
				if (filter.peakListAccepted(peakList)) {
					acceptedSpectra++;
					if (acceptedMgfWriter != null) {
						acceptedMgfWriter.writePeakList(peakList);
					}
				} else {
					rejectedSpectra++;
					if (rejectedMgfWriter != null) {
						rejectedMgfWriter.writePeakList(peakList);
					}
				}
			}

		} finally {
			FileUtilities.closeQuietly(acceptedMgfWriter);
			FileUtilities.closeQuietly(rejectedMgfWriter);
			FileUtilities.closeQuietly(sourceMgfReader);
		}

		return new MgfFilteredSpectraCount(totalSpectra, acceptedSpectra, rejectedSpectra);
	}


	/**
	 * The implementation of this method filteres a source mgf file by removing unwanted spectra.
	 * The unwanted spectra is defined in the badSpectraMGFTitle collection, which contains the title
	 * defining the bad spectra in the source mgf file. This method generates to output files, the filtered
	 * mgf file defined by the filteredMGFFileName parameter and the bad spectra mgf file defined by the
	 * badSpectraMGFFileName parameter.
	 *
	 * @param mgfSourceFileName     Source mgf file name.
	 * @param filteredMGFFileName   Filtered mgf file name, which is generated by this method.
	 * @param badSpectraMGFFileName Unwanted spectra mgf file name, which is generated by this method.
	 * @param badSpectraMGFTitles   Source mgf file bad spectra titles.
	 * @return int value representing the number of bad spectra removed from the mgf source file.
	 */
	public static int generateMGFFilteredFile(final String mgfSourceFileName, final String filteredMGFFileName, final String badSpectraMGFFileName, final Collection<String> badSpectraMGFTitles) {
		final TreeSet<String> copyOfBadSpectraCollection = new TreeSet<String>(badSpectraMGFTitles);
		final File sourceMgf = new File(mgfSourceFileName);
		final File acceptedMgf = new File(filteredMGFFileName);
		final File rejectedMgf = new File(badSpectraMGFFileName);
		final BadSpectraTitleFilter spectraFilter = new BadSpectraTitleFilter(copyOfBadSpectraCollection);

		final MgfFilteredSpectraCount count = filterMgfFile(sourceMgf, acceptedMgf, rejectedMgf, spectraFilter);

		return count.getRejectedSpectra();
	}
}
